# Generated by Django 2.2 on 2019-11-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tenant', '0001_initial'),
        ('app_surgeries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgerymodel',
            name='tenant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_tenant.Tenant'),
            preserve_default=False,
        ),
    ]
