# Generated by Django 2.2 on 2019-11-20 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tenant', '0001_initial'),
        ('core', '0002_auto_20191119_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_tenant.Tenant'),
            preserve_default=False,
        ),
    ]
