# Generated by Django 2.2 on 2019-11-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tenant',
        ),
    ]
